# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2

project_name: dbbench

before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/dbbench/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
archives:
  - format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next-{{.Commit}}"
# nfpms:
#   - maintainer: Simon Jürgensmeyyer <simon.juergensmeyer@gmail.com>
#     homepage: https://github.com/sj14/dbbench/
#     description: dbbench is a simple database benchmarking tool which supports several databases
#     license: MIT
#     formats:
#       - deb
#       - rpm
#       - apk # not tested
brews:
  - name: dbbench
    skip_upload: auto
    repository:
      owner: sj14
      name: homebrew-tap
    description: "dbbench is a simple database benchmarking tool which supports several databases"
release:
  github:
    owner: sj14
    name: dbbench
  disable: false
  draft: false
  prerelease: auto
changelog:
  filters:
    exclude:
      - typo
