name: Go

on:
  pull_request:
    paths:
      - go.sum
      - go.mod
      - "**.go"
      - .github/workflows/go.yaml

jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Format
        run: |
          go fmt ./...
          git diff --exit-code
      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false
      - name: Test
        run: go test -race ./...
